service: lambda-orchestrator

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    CUSTOMERS_API_BASE_URL: ${env:CUSTOMERS_API_BASE_URL}
    ORDERS_API_BASE_URL: ${env:ORDERS_API_BASE_URL}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  createAndConfirmOrder:
    handler: src/handlers/orchestrator.createAndConfirmOrder
    events:
      - http:
          path: /orchestrator/create-and-confirm-order
          method: post
          cors: true

custom:
  serverless-offline:
    httpPort: ${env:OFFLINE_HTTP_PORT, '3004'}
    lambdaPort: ${env:OFFLINE_LAMBDA_PORT, '3005'}
    noPrependStageInUrl: true
